In [5]:
#for making alterations to TF binding motifs after getting sequences in SuPreMo

In [6]:
%load_ext autoreload
%autoreload 2

In [24]:
import basenji
import pandas as pd 
import numpy as np
import os, psutil, io, gzip, time 
import pysam
import warnings
import random 

import matplotlib.pyplot as plt
import seaborn as sns
from pybedtools import BedTool

In [8]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)
pd.set_option('display.width', 1000)

In [9]:
hg38_file = '/home/data/genomes/hg38.fa'
hg38_fa = pysam.Fastafile(hg38_file)

In [10]:
colnames = ['CHROM', 'POS', 'END', 'REF', 'ALT', 'SVTYPE', 'SVLEN']

test_dir='/home/shu_zhang/SuPreMo/test_data/test_set_edge_cases/'
test_sv=pd.read_csv(f'{test_dir}test_set_edge_SV.bed', sep='\t', names=colnames)
test_sv_no_bnd=test_sv[test_sv.SVTYPE!='BND']
test_simple=pd.read_csv(f'{test_dir}test_set_edge_simple.bed', sep='\t', names=colnames)

In [11]:
variants=test_sv_no_bnd
variants

    CHROM        POS          END                                                REF           ALT SVTYPE   SVLEN
0    chr1  244397848  244398348.0  AAACTAAACTAAAATAAACTAAAATAAACTAAAATAAACTAAACTA...             A    DEL   500.0
1    chr1  244397848  244398348.0                                                  A         <DEL>    DEL   500.0
2    chr1  244397848  244398348.0                                                  A  <DUP:TANDEM>    DUP   500.0
3    chr1  244397848  244398348.0                                                  A         <INV>    INV   500.0
4    chr1  244397848  244402848.0                                                  A         <DEL>    DEL  5000.0
5    chr1  244397848  244402848.0                                                  A  <DUP:TANDEM>    DUP  5000.0
6    chr1  244397848  244402848.0                                                  A         <INV>    INV  5000.0
7    chr2     400000     400500.0  CTATGGAACAGGCTGGGGTTACTTGGCTATAGAACAGGCCGGGGCC...             C    DEL   500.0
8    chr2     400000     400500.0                                                  C         <DEL>    DEL   500.0
9    chr2     400000     400500.0                                                  C  <DUP:TANDEM>    DUP   500.0
10   chr2     400000     400500.0                                                  C         <INV>    INV   500.0
11   chr2     400000     405000.0                                                  C         <DEL>    DEL  5000.0
12   chr2     400000     405000.0                                                  C  <DUP:TANDEM>    DUP  5000.0
13   chr2     400000     405000.0                                                  C         <INV>    INV  5000.0
14  chr10   37600000   37600500.0  GCCATCTTAATTGTGATGAGGTGATATCTCAATGTAGTTTTCATTT...             G    DEL   500.0
15  chr10   37600000   37600500.0                                                  G         <DEL>    DEL   500.0
16  chr10   37600000   37600500.0                                                  G  <DUP:TANDEM>    DUP   500.0
17  chr10   37600000   37600500.0                                                  G         <INV>    INV   500.0
18  chr10   37600000   37605000.0                                                  G         <DEL>    DEL  5000.0
19  chr10   37600000   37605000.0                                                  G  <DUP:TANDEM>    DUP  5000.0
20  chr10   37600000   37605000.0                                                  G         <INV>    INV  5000.0
21   chr3   94400000   94400500.0  TTCTCTTTAGGGTGGCCTACAGATTTTGCTGTAGTTAAATTCCTTC...             T    DEL   500.0
22   chr3   94400000   94400500.0                                                  T         <DEL>    DEL   500.0
23   chr3   94400000   94400500.0                                                  T  <DUP:TANDEM>    DUP   500.0
24   chr3   94400000   94400500.0                                                  T         <INV>    INV   500.0
25   chr3   94400000   94405000.0                                                  T         <DEL>    DEL  5000.0
26   chr3   94400000   94405000.0                                                  T  <DUP:TANDEM>    DUP  5000.0
27   chr3   94400000   94405000.0                                                  T         <INV>    INV  5000.0
28   chr1  248766420  248766920.0  ACCAAAACAGAGAGATAGATCAATGGAACAGAACAGAGCCCTCAGA...             A    DEL   500.0
29   chr1  248766420  248766920.0                                                  A         <DEL>    DEL   500.0
30   chr1  248766420  248766920.0                                                  A  <DUP:TANDEM>    DUP   500.0
31   chr1  248766420  248766920.0                                                  A         <INV>    INV   500.0
32   chr1  248766420  248771420.0                                                  A         <DEL>    DEL  5000.0
33   chr1  248766420  248771420.0                                                  A  <DUP:TANDEM>    DUP  5000.0
34   chr1  248766420  248771420.0                                                  A         <INV>    INV  5000.0
35  chr11   52000000   52000500.0  CCTTCGAAACGGGTATATCTTCACATCAAACCTAGACAGGAAGCAT...             C    DEL   500.0
36  chr11   52000000   52000500.0                                                  C         <DEL>    DEL   500.0
37  chr11   52000000   52000500.0                                                  C  <DUP:TANDEM>    DUP   500.0
38  chr11   52000000   52000500.0                                                  C         <INV>    INV   500.0
39  chr11   52000000   52005000.0                                                  C         <DEL>    DEL  5000.0
40  chr11   52000000   52005000.0                                                  C  <DUP:TANDEM>    DUP  5000.0
41  chr11   52000000   52005000.0                                                  C         <INV>    INV  5000.0

In [37]:
POS=244397848
END=244398348


var_rel_pos=524038

In [39]:
#read in CTCF overlap file
ctcf_track=pd.read_csv('/home/shu_zhang/SuPreMo/mutate_data/MA0139.2.tsv.gz', sep='\t', names=['chr', 'start', 'end', 'tf', 'idk1' ,'idk2', 'idk3'])
#just look at the one for the first few variants in supremo 
#subset to within 1MB
#these variants are in normal range, i think
#ctcf_chr1=ctcf_track[(ctcf_track.chr=='chr1') & (ctcf_track.start>243397848) & (ctcf_track.end<245397848)]

flank_len=10000
ctcf_chr1=ctcf_track[(ctcf_track.chr=='chr1') & (ctcf_track.start>(POS-flank_len)) & (ctcf_track.end<(END+flank_len))]

ctcf_chr1['span']=ctcf_chr1['end']-ctcf_chr1['start']

ctcf_chr1['diff_from_POS']=ctcf_chr1['start'] - POS
ctcf_chr1['motif_start_idx']=var_rel_pos + ctcf_chr1['diff_from_POS']
ctcf_chr1['motif_end_idx']=ctcf_chr1['motif_start_idx'] + ctcf_chr1['span']

track_df=ctcf_chr1
#track_df[0:5]


#turn this into the list of tuples 
tuple_coordinates = list(zip(ctcf_chr1['motif_start_idx'], ctcf_chr1['motif_end_idx']))
tuple_coordinates

/tmp/ipykernel_29504/4154077549.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ctcf_chr1['span']=ctcf_chr1['end']-ctcf_chr1['start']
/tmp/ipykernel_29504/4154077549.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ctcf_chr1['diff_from_POS']=ctcf_chr1['start'] - POS
/tmp/ipykernel_29504/4154077549.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ctcf_chr1['motif_start_idx']=var_rel_pos + ctcf_chr1['diff_from_POS']
/tmp/ipykernel_29504/4154077549.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ctcf_chr1['motif_end_idx']=ctcf_chr1['motif_start_idx'] + ctcf_chr1['span']

[(516301, 516316),
 (516494, 516509),
 (518085, 518100),
 (518268, 518283),
 (518675, 518690),
 (518677, 518692),
 (520717, 520732),
 (521391, 521406),
 (521713, 521728),
 (523924, 523939),
 (524401, 524416),
 (527408, 527423),
 (530861, 530876),
 (531594, 531609),
 (531750, 531765),
 (532513, 532528)]

In [ ]:
#now, turn this into a list of tuples

In [20]:
np.mean(track_df['span'])

15.0

In [28]:
#check thatn sum of regions is not larger than 1024
if sum(track_df['span']) > 100:

    average_span=np.mean(track_df['span'])
    estimated_rows = min(int(100 / average_span), len(track_df))

    # Sample rows from the DataFrame without replacement
    sampled_track_df = track_df.sample(n=estimated_rows)

    # Calculate the total sum of spans in the sampled DataFrame
    total_span = sampled_track_df['span'].sum()

    # If the total span exceeds 100, remove rows until it's under 100
    while total_span > 100 and len(sampled_track_df) > 0:
        # Get the row with the maximum span
        max_span_row = sampled_track_df.loc[sampled_track_df['span'].idxmax()]
    
        # Remove the row from the sampled DataFrame
        sampled_track_df = sampled_track_df.drop(max_span_row.name)
    
        # Update the total span
        total_span -= max_span_row['span']

else:
    sampled_track_df=track_df

In [29]:
sampled_track_df

         chr      start        end    tf  idk1  idk2 idk3  span
174919  chr1  244398211  244398226  CTCF   828   388    -    15
174924  chr1  244406323  244406338  CTCF   803   348    -    15
174910  chr1  244390304  244390319  CTCF   860   445    -    15
174923  chr1  244405560  244405575  CTCF   802   348    -    15
174917  chr1  244395523  244395538  CTCF   826   386    +    15
174915  chr1  244394527  244394542  CTCF   851   429    -    15

In [ ]:
#next, need to turn these numbers into indices relative to POS

In [13]:
hg38_fa.fetch('chr1', 24439500, 24439600).upper()

'TTAAAAGTGACTTTTCTATTATGGTGGTGTTGTTATTGTTATTTTTTTCATTTTTTTCTCATGCTACCTTGTCTAAGATATTATTATTTTTATCTATATA'

In [ ]:
#what we get out of supremo:
#sequences
#var_rel_pos --> gives start of variant for REF_ALT, based on position from 0 (start of sequence)

In [40]:
#THIS IS FOR INV

def invert_motifs(sequence, substr_ranges):
    seq_list = list(sequence)  
    
    for start, end in substr_ranges:
        # Invert the substring within the list
        seq_list[start:end] = seq_list[start:end][::-1]
        
    # Convert the list back to a string
    return ''.join(seq_list)

# Example usage:
string = "abcdefgh"
coordinates_to_invert = [(1, 3), (5, 8)]  # Coordinates to invert (start, end)
result = invert_motifs(string, coordinates_to_invert)
print(result)  # Output: 'acbdehgf'

acbdehgf

In [41]:
#THIS IS FOR SHUFFLING
def shuffle_motifs(sequence, substr_ranges):
    seq_list = list(sequence)

    # Shuffle nucleotides within each substring
    for start, end in substr_ranges:
        # Extract the substring
        substring = seq_list[start:end]

        # Shuffle the substring in-place
        random.shuffle(substring)

        # Update the sequence with the shuffled substring
        seq_list[start:end] = substring
    
    return ''.join(seq_list)

# Example usage:
# this seems to work.... lol 
sequence = "ATGCATCGATCGATCG"
substr_ranges = [(2, 7), (11,16)]  # Example substring ranges
shuffled_sequence = shuffle_motifs(sequence, substr_ranges)
print(shuffled_sequence)

ATCTCAGGATCCTGGA

In [1]:
def mutate_TFs(CHR, POS, END, SVTYPE, SVLEN, sequences_i, tf_mutate_type, up_flank, down_flank, revcomp, alter_variant, track_path):

    """
    This function mutates TFs within the variant and its flanking region
    

    Note to self: use a different function for shuffling motifs, that one is easier / doesn't need to count up to 1024s
    
    Arguments:
        up_flank: 
            - length of bp upstream of variant to look for TF motifs 
        down_flank:
            - length of bp downstream of variant to look for TF motifs    
        tf_mutate_type:
            - how we want to alter the tf motif
            -options: "INV", "shuffle"
        alter_variant: 
            - if True, we use the ALT sequence (variant included)
            - if False, we use the REF sequence (variant not included) 
            - THIS IS CURRENTLY NOT IMPLEMENETED
        track_path: 
            - path to TF binding track. For now, must be JASPAR-style bed tracks 

    Returns: 
        sequences_i: tuple containing:
            1. REF sequence (index 0)
            2. REF-altered sequence based on the TF motifs (index 1)
            3. variant POS indices relative to start for [REF, ALT] (index 2)

    
        Note to self: this is different for BNDs!!!!!!!!!!!!!!!!

        Note to self: might want to make this compatible with multiple TFs in the future?? maybe? would get complicated

    """

    if SVTYPE=='BND':
        #FIX THIS LATER 
        return(sequences_i)


    # check that if using flanking regions, they are within the length of the sequence    
    var_rel_pos=sequences_i[-1][0]     #this one is based on the REF sesquence 
    var_rel_end=var_rel_pos+SVLEN    #this one is based on the REF sesquence 
    sequence=sequences_i[0]

    if (var_rel_pos - up_flank) < 0 or (var_rel_end + down_flank) > len(seq):
        raise ValueError("Flanking indices exceed available sequence length")

   
    # read in track 
    track_cols=['chr', 'start', 'end', 'tf', 'rel_score', '-log10(pval)', 'strand']
    track_df=pd.read_csv(track_path, sep='\t', header=None, skiprows=1, names=track_cols) 
    track_df['start']=track_df['start'].astype(int)
    track_df['end']=track_df['end'].astype(int)
    track_df['span']=track_df['end']-ctcf_chr1['start']
    #tf_name=track_df.iloc[1,3]

    #get track df surrounding the variant
    track_df_variant=track_df[(track_df.chr==POS) & (track_df.start>(POS-flank_len)) & (track_df.end<(END+flank_len))]

    #later, may want to include option to only look at flanking regions and not include the variant itself 

    #the below only applies if we use deletions/duplications. for now, we don't need this 
    
    # #NEED TO CHECK THAT TOTAL MOTIF LENGTH IN REGION IS <1024
    # #IF NOT, NEED TO SAMPLE UNTIL MAX 1024 
    # if sum(track_df_variant['span']) > 100:

    #     average_span=np.mean(track_df_variant['span'])
    #     estimated_rows = min(int(100 / average_span), len(track_df_variant))

    #     # Sample rows from the DataFrame without replacement
    #     sampled_track_df = track_df_variant.sample(n=estimated_rows)

    #     # Calculate the total sum of spans in the sampled DataFrame
    #     total_span = sampled_track_df['span'].sum()

    #     # If the total span exceeds 100, remove rows until it's under 100
    #     while total_span > 100 and len(sampled_track_df) > 0:
            
    #         # get the row with the maximum span and remove 
    #         max_span_row = sampled_track_df.loc[sampled_track_df['span'].idxmax()]
    #         sampled_track_df = sampled_track_df.drop(max_span_row.name)
    
    #         # Update the total span
    #         total_span -= max_span_row['span']

    # else:
    #     sampled_track_df=track_df

   
    #get locations of each motif for within each sequence  
    track_df_variant['diff_from_POS']=track_df_variant['start'] - POS
    track_df_variant['motif_start_idx']=var_rel_pos + track_df_variant['diff_from_POS']
    track_df_variant['motif_end_idx']=track_df_variant['motif_start_idx'] + track_df_variant['span']

    
    # if REVCOMP, need to invert these indices
    # DOUBLE CHECK THAT THIS IS CORRECT I AM WORRIED
    if revcomp:
        #also make sure these are not one off 
        track_df_variant['motif_start_idx_revcomp']=len(sequence)- track_df_variant['motif_end_idx']
        track_df_variant['motif_end_idx_revcomp']=len(sequence)- track_df_variant['motif_start_idx']
        
        #turn this into the list of tuples 
        tuple_coordinates = list(zip(ctcf_chr1['motif_start_idx_revcomp'], ctcf_chr1['motif_end_idx_revcomp']))

    else:
        #turn this into the list of tuples 
        tuple_coordinates = list(zip(ctcf_chr1['motif_start_idx'], ctcf_chr1['motif_end_idx']))



    #finally, alter sequences based on which alteration
    #current choices are only shuffling or inverting 


    if tf_mutate_type=='INV':
        new_seq=invert_motifs(sequence, tuple_coordinates):

    elif tf_mutate_type=='shuffle':
        new_seq=shuffle_motifs(sequence, tuple_coordinates)

    else:
        raise Exception("No suitable TF mutate option selected")

        
    #for now, replace the alt seq with the gc mutated seq
    sequences_i_list=list(sequences_i)
    sequences_i_list[1]=new_seq
    sequences_i=tuple(sequences_i_list)

    #returns REF and GC-altered REF atm 
    return(sequences_i)

In [ ]:
#SAVE DEL AND DUP FOR LATER, OR NEVER
#BECAUSE SEQUENCES WILL SHIFT AROUND AND WILL BE HARD TO CENTER VARIANT AGAIN

In [ ]:
#NOTE TO SELF: NEED TO GET LIST/TUPLE OF MOTIF COORDINATES AND REMOVE THEM

#this is only for DEL

def remove_substrings(seq, coordinates):
    result = ""
    index = 0
    
    for start, end in coordinates:
        result += seq[index:start]
        index = end + 1
    
    result += seq[index:]
    
    return result


string = "abcdefgh"
coordinates_to_remove = [(1, 3), (5, 6)]
result = remove_substrings(string, coordinates_to_remove)
print(result)  #

In [ ]:
#THIS IS FOR DUP 

def duplicate_substrings(string, coordinates):
    result = ""
    index = 0
    
    for start, end in coordinates:
        result += string[index:start]  # Add substring before the duplicate
        substring_to_duplicate = string[start:end+1]  # Extract substring to duplicate
        result += substring_to_duplicate  # Add original substring
        result += substring_to_duplicate  # Add duplicated substring
        index = end + 1
    
    result += string[index:]  # Add remaining substring
    
    return result

# Example usage:
string = "abcdefgh"
coordinates_to_duplicate = [(1, 3), (5, 8)]  # Coordinates to duplicate (start, end)
result = duplicate_substrings(string, coordinates_to_duplicate)
print(result)  #